Add logics for Atomic Operation and Burst Messages.
merledu/caravan pull request #18
Opened 2023-05-14 13:09 UTC by siddiquimohsin

Added the logic in two files **Tile link Device.scala** and **Tile Link Host.scala**.

1. Added the logic for Atomic Operation in Tile Link Device.
2. Added the logic for Burst Message in Tile Link Device and Tile Link Host both.
3. Added Regression Test file called **TLUH Test.scala**, generating random data, opcode and parameter for testing purpose.

2023-05-27 16:23 UTC, shahzaibk23 requested changes

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkBus.scala
> +  val is_arithmetic = if(config.uh) Some(Bool()) else None
This should follow one coding style either camelCase or snake_case. Above code follows camelCase so I'd suggest to update these variable names a/c to the consistent pattern.

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkConfig.scala
> +    val z: Int = 8,
kindly do not change the Config parameters directly in the case class. Instead update their values in Harness/Test or the place where you are instantiating it

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkConfig.scala
> +    // TL-UH
I'd suggest to move this comment upwards, where all parameters' description is written.

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    when(stateReg =/= idle){
Is this a workable condition? Can you state the purpose of this block. Why is it necessary to check the stateReg every cycle and turn it idle if it's in any other state? Does it not break the flow of operations?

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    val counter_D = RegInit(UInt(config.z.W),0.U)
shouldn't it be `RegInit(0.U(config.z.W))`

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    val add_reg_D = RegInit(0.U)
once again, keep coding style consistent (i.e camelCase)

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    io.reqOut.bits.is_arithmetic.get := false.B
give an indent of 1 TAB, so the code inside codeblock distinguishes with the one outside

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +       //val idle :: wait_for_resp :: Nil = Enum(2)
remove unnecessary commented code, if you think it'll never be needed in the future

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +            when(op_reg_D =/= 6.U && ((1.U << io.tlMasterReceiver.bits.a_size).asUInt() > config.w.U)){
can you add some tiny comments here to describe the opcode operation and what this codeblock is doing, will be better for debugging

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +            io.reqOut.bits.isWrite := false.B
why are you hard-wiring it?

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    val idle :: uh :: wait_for_resp :: Nil = Enum(3)
add a descriptive comment here to describe the usecases of all 3 of the states

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +                io.reqOut.bits.dataRequest := MuxCase(io.rspIn.bits.dataResponse,  Array(
just a suggestion you can create nested muxcases instead of inserting everything inside one Array

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +            when(op_reg_D =/= 6.U && ((1.U << io.tlMasterReceiver.bits.a_size).asUInt() > config.w.U)){
Also, why are you not using the values from OpCode Singleton Class extended above, why are you writing OpCode's value directly?

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkHost.scala
> +            //io.tlMasterTransmitter.bits.a_opcode := op_reg
remove not needed commented code

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkOpcodes.scala
> +    val HintAck = 2
It doesn't contain OpCode 6?

2023-05-27 16:23 UTC, shahzaibk23 commented on src/test/scala/tilelink/New_Test.scala
> +package tilelink
remove this file, it was only for debugging, not needed to be merged!!!

2023-05-27 16:23 UTC, shahzaibk23 commented on src/test/scala/tilelink/SwitchHarnessTest.scala
> +        //c.io.valid.poke(false.B)
may i ask the reasons for disabling valid turn offs after 1 cycle?

2023-05-27 16:23 UTC, shahzaibk23 commented on src/main/scala/caravan/bus/tilelink/TilelinkBus.scala
> +  val is_arithmetic = if(config.uh) Some(Bool()) else None
@siddiquimohsin

2023-05-27 19:00 UTC, devchadha-jmi commented on src/test/scala/tilelink/New_Test.scala
> +package tilelink
This file is now removed.

2023-05-27 19:04 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkOpcodes.scala
> +    val HintAck = 2
Added opcode NoOp in opcode file which has a value 6.

2023-05-27 19:07 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkHost.scala
> +            //io.tlMasterTransmitter.bits.a_opcode := op_reg
Removed commented code.

2023-05-27 19:14 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    val idle :: uh :: wait_for_resp :: Nil = Enum(3)
Added description of states to the code.

2023-05-27 19:18 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +            io.reqOut.bits.isWrite := false.B
Since, we are in idle state, where we have to perform read operation, the isWrite signal is hard-wired to false.

2023-05-27 19:20 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +            when(op_reg_D =/= 6.U && ((1.U << io.tlMasterReceiver.bits.a_size).asUInt() > config.w.U)){
We have changed this logic in the latest code.

2023-05-27 19:20 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +       //val idle :: wait_for_resp :: Nil = Enum(2)
Done.

2023-05-27 19:25 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    io.reqOut.bits.is_arithmetic.get := false.B
Indentations added.

2023-05-27 19:40 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    val add_reg_D = RegInit(0.U)
Changed the case

2023-05-27 19:41 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkDevice.scala
> +    when(stateReg =/= idle){
The logic is changed in latest code

2023-05-27 19:43 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkConfig.scala
> +    // TL-UH
Done

2023-05-27 19:47 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkConfig.scala
> +    val z: Int = 8,
Done.

2023-05-27 19:47 UTC, devchadha-jmi commented on src/main/scala/caravan/bus/tilelink/TilelinkBus.scala
> +  val is_arithmetic = if(config.uh) Some(Bool()) else None
The case has been changed

2023-05-28 10:28 UTC, shahzaibk23 commented
@devchadha-jmi can you mark the changes as **_resolved_** that you have resolved in the latest commit?

2023-05-28 16:59 UTC, shahzaibk23 approved these changes

2023-05-30 17:45 UTC, shahzaibk23 commented
All looks good

2023-05-30 17:46 UTC, merged